name: Codacy Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true
