---
name: Development release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Test
        run: go test -v ./...

  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 202533543271.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build, tag and push Docker image
        run: |
          docker build -t day-ahead-prices-notificator .
          docker tag day-ahead-prices-notificator:latest 202533543271.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker push 202533543271.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Add GitHub Runner IP to Security Group
        run: |
          GITHUB_IP=$(curl -s https://api64.ipify.org)
          aws ec2 authorize-security-group-ingress --group-id sg-0c30e26b4661ff7d4 --protocol tcp --port 22 --cidr $GITHUB_IP/32

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop day-ahead-prices-notificator
            sudo docker rm day-ahead-prices-notificator
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 202533543271.dkr.ecr.eu-north-1.amazonaws.com
            sudo docker pull 202533543271.dkr.ecr.eu-north-1.amazonaws.com/202533543271:latest
            sudo docker run -d -p 80:80 --name day-ahead-prices-notificator --env-file .env 202533543271.dkr.ecr.eu-north-1.amazonaws.com/day-ahead-prices-notificator:latest

      - name: Remove GitHub Runner IP from Security Group
        run: |
          GITHUB_IP=$(curl -s https://api64.ipify.org)
          aws ec2 revoke-security-group-ingress --group-id sg-0c30e26b4661ff7d4 --protocol tcp --port 22 --cidr $GITHUB_IP/32
